
import { MenuItem, TranslationSet, Language } from './types';

export const LANGUAGES: { code: Language; name: string; flag: string }[] = [
  { code: 'nl', name: 'Nederlands', flag: '🇳🇱' },
  { code: 'el', name: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
  { code: 'ar', name: 'العربية', flag: '🇦🇪' },
  { code: 'bg', name: 'Български', flag: '🇧🇬' },
  { code: 'pl', name: 'Polski', flag: '🇵🇱' },
];

const adminCommon = {
  adminDashboard: "Admin Dashboard",
  activeOrders: "Actieve Bestellingen",
  orderStatus: {
    pending: "In Afwachting",
    preparing: "Bereiden",
    ready: "Klaar",
    delivery: "Onderweg",
    completed: "Voltooid",
    cancelled: "Geannuleerd"
  },
  paymentStatus: {
    unpaid: "Onbetaald",
    pending: "Bezig",
    paid: "Betaald",
    failed: "Mislukt",
    refunded: "Terugbetaald"
  },
  printReceipt: "Bon Printen",
  deliveryAddress: "Bezorgadres",
  finishOrder: "Bestelling Afronden",
  // Checkout translations NL
  checkoutTitle: "Afrekenen",
  deliveryDetails: "Bezorggegevens",
  paymentMethod: "Betaalmethode",
  orderSummary: "Besteloverzicht",
  subtotal: "Subtotaal",
  deliveryFee: "Bezorgkosten",
  totalToPay: "Te betalen",
  payNow: "Nu Betalen",
  processing: "Bezig met verwerken...",
  paymentSuccess: "Betaling geslaagd!",
  paymentFailed: "Betaling mislukt",
  tryAgain: "Probeer opnieuw",
  backToMenu: "Terug naar menu",
  orderConfirmed: "Bestelling bevestigd!",
  orderNumber: "Bestelnummer",
  estimatedTime: "Geschatte tijd",
  trackOrder: "Volg bestelling",
  pickupAddress: "Ophaaladres",
  deliveryOption: "Bezorgen",
  pickupOption: "Afhalen",
  idealPayment: "iDEAL",
  cardPayment: "Creditcard",
  cashPayment: "Contant bij bezorging",
  invalidPostalCode: "Ongeldige postcode",
  denHaagOnly: "We bezorgen alleen in Den Haag",
  requiredField: "Dit veld is verplicht",
  invalidEmail: "Ongeldig e-mailadres",
  invalidPhone: "Ongeldig telefoonnummer",
  minOrderAmount: "Minimale bestelling: €15",
  freeDeliveryFrom: "Gratis bezorging vanaf €35",
  // Admin panel navigation
  staffConsole: "Personeelsconsole",
  greekIriniPremium: "Greek Irini Premium",
  liveLink: "Live Link Actief",
  liveOrders: "Live Bestellingen",
  history: "Geschiedenis",
  reservations: "Reserveringen",
  analytics: "Analyse",
  menuManagement: "Menu Beheer",
  settings: "Instellingen",
  periodicReport: "Periodiek Rapport",
  financialInsight: "Financieel Inzicht",
  // Orders
  serviceQueue: "Servicewachtrij",
  activeRequests: "Actieve Verzoeken",
  searchOrders: "Zoek bestellingen...",
  noOrdersFound: "Geen bestellingen gevonden voor deze weergave.",
  // Reservations
  pendingReservations: "Wachtende Reserveringen",
  noPendingReservations: "Geen wachtende reserveringen",
  date: "Datum",
  time: "Tijd",
  guests: "Gasten",
  phone: "Telefoon",
  specialRequests: "Speciale Verzoeken",
  adminNotes: "Notities voor bevestiging",
  adminNotesPlaceholder: "Bijv. tafel bij het raam gereserveerd...",
  confirmAndSendEmail: "Bevestig en Verstuur Email",
  rejectReservation: "Weiger Reservering",
  close: "Sluiten",
  reservationStatus: {
    pending: "Wachtend",
    confirmed: "Bevestigd",
    rejected: "Geweigerd",
    cancelled: "Geannuleerd"
  },
  confirmed: "bevestigd",
  pending: "wachtend",
  persons: "pers.",
  reservationsFor: "Reserveringen voor",
  noReservationsThisDay: "Geen reserveringen op deze dag",
  totalGuests: "Totaal gasten",
  confirmedRes: "Bevestigd",
  pendingRes: "Wachtend",
  confirmationSentAt: "Bevestiging verstuurd op",
  weekDays: ['Ma', 'Di', 'Wo', 'Do', 'Vr', 'Za', 'Zo'],
  home: "Home",
  reservationNav: "Reserveren",
  // Analytics
  revenueByCategory: "Omzet per Categorie",
  topBestsellers: "Top 5 Bestsellers",
  revenue: "Omzet",
  totalOrders: "Totaal Bestellingen",
  avgOrderValue: "Gem. Bestelwaarde",
  dishesSold: "Verkochte Gerechten",
  peakHours: "Piekuren",
  hourlyOrders: "Bestellingen per Uur",
  revenueOverTime: "Omzet in de Tijd",
  categoryBreakdown: "Categorieverdeling",
  deliveryStats: "Bezorgstatistieken",
  paymentMethods: "Betaalmethoden",
  weekdayTrends: "Weekdag Trends",
  // Menu management
  addNewItem: "Nieuw Item Toevoegen",
  editItem: "Item Bewerken",
  deleteItem: "Item Verwijderen",
  available: "Beschikbaar",
  unavailable: "Niet beschikbaar",
  units: "Eenheden"
};

const elAdmin = {
  adminDashboard: "Πίνακας Διαχείρισης",
  activeOrders: "Ενεργές Παραγγελίες",
  orderStatus: {
    pending: "Σε Αναμονή",
    preparing: "Προετοιμασία",
    ready: "Έτοιμο",
    delivery: "Σε Διανομή",
    completed: "Ολοκληρώθηκε",
    cancelled: "Ακυρώθηκε"
  },
  paymentStatus: {
    unpaid: "Απλήρωτο",
    pending: "Σε Εξέλιξη",
    paid: "Πληρώθηκε",
    failed: "Απέτυχε",
    refunded: "Επιστράφηκε"
  },
  printReceipt: "Εκτύπωση Απόδειξης",
  deliveryAddress: "Διεύθυνση Παράδοσης",
  finishOrder: "Ολοκλήρωση Παραγγελίας",
  checkoutTitle: "Ολοκλήρωση Αγοράς",
  deliveryDetails: "Στοιχεία Παράδοσης",
  paymentMethod: "Μέθοδος Πληρωμής",
  orderSummary: "Σύνοψη Παραγγελίας",
  subtotal: "Υποσύνολο",
  deliveryFee: "Κόστος Παράδοσης",
  totalToPay: "Σύνολο Πληρωμής",
  payNow: "Πληρωμή Τώρα",
  processing: "Επεξεργασία...",
  paymentSuccess: "Η πληρωμή ολοκληρώθηκε!",
  paymentFailed: "Η πληρωμή απέτυχε",
  tryAgain: "Δοκιμάστε ξανά",
  backToMenu: "Επιστροφή στο Μενού",
  orderConfirmed: "Η παραγγελία επιβεβαιώθηκε!",
  orderNumber: "Αριθμός Παραγγελίας",
  estimatedTime: "Εκτιμώμενος Χρόνος",
  trackOrder: "Παρακολούθηση Παραγγελίας",
  pickupAddress: "Διεύθυνση Παραλαβής",
  deliveryOption: "Παράδοση",
  pickupOption: "Παραλαβή",
  idealPayment: "iDEAL",
  cardPayment: "Πιστωτική Κάρτα",
  cashPayment: "Μετρητά κατά την παράδοση",
  invalidPostalCode: "Μη έγκυρος ταχυδρομικός κώδικας",
  denHaagOnly: "Παραδίδουμε μόνο στη Χάγη",
  requiredField: "Αυτό το πεδίο είναι υποχρεωτικό",
  invalidEmail: "Μη έγκυρη διεύθυνση email",
  invalidPhone: "Μη έγκυρος αριθμός τηλεφώνου",
  minOrderAmount: "Ελάχιστη παραγγελία: €15",
  freeDeliveryFrom: "Δωρεάν παράδοση από €35",
  staffConsole: "Κονσόλα Προσωπικού",
  greekIriniPremium: "Greek Irini Premium",
  liveLink: "Ζωντανός Σύνδεσμος Ενεργός",
  liveOrders: "Ζωντανές Παραγγελίες",
  history: "Ιστορικό",
  reservations: "Κρατήσεις",
  analytics: "Αναλυτικά",
  menuManagement: "Διαχείριση Μενού",
  settings: "Ρυθμίσεις",
  periodicReport: "Περιοδική Αναφορά",
  financialInsight: "Οικονομική Ανάλυση",
  serviceQueue: "Ουρά Εξυπηρέτησης",
  activeRequests: "Ενεργά Αιτήματα",
  searchOrders: "Αναζήτηση παραγγελιών...",
  noOrdersFound: "Δεν βρέθηκαν παραγγελίες για αυτήν την προβολή.",
  pendingReservations: "Κρατήσεις σε Αναμονή",
  noPendingReservations: "Δεν υπάρχουν κρατήσεις σε αναμονή",
  date: "Ημερομηνία",
  time: "Ώρα",
  guests: "Επισκέπτες",
  phone: "Τηλέφωνο",
  specialRequests: "Ειδικά Αιτήματα",
  adminNotes: "Σημειώσεις για επιβεβαίωση",
  adminNotesPlaceholder: "π.χ. κρατήθηκε τραπέζι δίπλα στο παράθυρο...",
  confirmAndSendEmail: "Επιβεβαίωση και Αποστολή Email",
  rejectReservation: "Απόρριψη Κράτησης",
  close: "Κλείσιμο",
  reservationStatus: {
    pending: "Σε Αναμονή",
    confirmed: "Επιβεβαιωμένη",
    rejected: "Απορρίφθηκε",
    cancelled: "Ακυρώθηκε"
  },
  confirmed: "επιβεβαιωμένη",
  pending: "σε αναμονή",
  persons: "άτομα",
  reservationsFor: "Κρατήσεις για",
  noReservationsThisDay: "Δεν υπάρχουν κρατήσεις αυτή την ημέρα",
  totalGuests: "Σύνολο επισκεπτών",
  confirmedRes: "Επιβεβαιωμένες",
  pendingRes: "Σε Αναμονή",
  confirmationSentAt: "Επιβεβαίωση στάλθηκε στις",
  weekDays: ['Δευ', 'Τρί', 'Τετ', 'Πέμ', 'Παρ', 'Σάβ', 'Κυρ'],
  home: "Αρχική",
  reservationNav: "Κράτηση",
  revenueByCategory: "Έσοδα ανά Κατηγορία",
  topBestsellers: "Top 5 Μπεστ Σέλερ",
  revenue: "Έσοδα",
  totalOrders: "Σύνολο Παραγγελιών",
  avgOrderValue: "Μέση Αξία Παραγγελίας",
  dishesSold: "Πιάτα που Πουλήθηκαν",
  peakHours: "Ώρες Αιχμής",
  hourlyOrders: "Παραγγελίες ανά Ώρα",
  revenueOverTime: "Έσοδα στον Χρόνο",
  categoryBreakdown: "Ανάλυση Κατηγορίας",
  deliveryStats: "Στατιστικά Παράδοσης",
  paymentMethods: "Μέθοδοι Πληρωμής",
  weekdayTrends: "Τάσεις Καθημερινών",
  addNewItem: "Προσθήκη Νέου Προϊόντος",
  editItem: "Επεξεργασία Προϊόντος",
  deleteItem: "Διαγραφή Προϊόντος",
  available: "Διαθέσιμο",
  unavailable: "Μη Διαθέσιμο",
  units: "Μονάδες",
  heroTitle: "Αυθεντική Ελληνική Γεύση",
  heroSub: "Από την οικογένειά μας στο τραπέζι σας. Απολαύστε τα καλύτερα της Ελλάδας.",
  orderNow: "Παραγγείλετε Τώρα",
  ourMenu: "Μενού",
  aboutUs: "Σχετικά",
  contact: "Επικοινωνία",
  cart: "Καλάθι",
  total: "Σύνολο",
  addToCart: "Προσθήκη",
  categories: { 
    mains: "Κυρίως Πιάτα", 
    starters_cold: "Κρύα Ορεκτικά", 
    starters_warm: "Ζεστά Ορεκτικά", 
    salads: "Σαλάτες", 
    desserts: "Επιδόρπια" 
  },
  emptyCart: "Το καλάθι είναι άδειο",
  checkout: "Ολοκλήρωση",
  contactTitle: "Επικοινωνήστε",
  contactSubtitle: "Έχετε ερωτήσεις; Χαρά μας να βοηθήσουμε.",
  formName: "Όνομα",
  formEmail: "Email",
  formMessage: "Μήνυμα",
  formSubmit: "Αποστολή",
  writeReview: "Γράψτε κριτική"
};

const trAdmin = {
  adminDashboard: "Yönetici Paneli",
  activeOrders: "Aktif Siparişler",
  orderStatus: {
    pending: "Beklemede",
    preparing: "Hazırlanıyor",
    ready: "Hazır",
    delivery: "Yolda",
    completed: "Tamamlandı",
    cancelled: "İptal Edildi"
  },
  paymentStatus: {
    unpaid: "Ödenmedi",
    pending: "İşleniyor",
    paid: "Ödendi",
    failed: "Başarısız",
    refunded: "İade Edildi"
  },
  printReceipt: "Fiş Yazdır",
  deliveryAddress: "Teslimat Adresi",
  finishOrder: "Siparişi Tamamla",
  checkoutTitle: "Ödeme",
  deliveryDetails: "Teslimat Bilgileri",
  paymentMethod: "Ödeme Yöntemi",
  orderSummary: "Sipariş Özeti",
  subtotal: "Ara Toplam",
  deliveryFee: "Teslimat Ücreti",
  totalToPay: "Ödenecek Tutar",
  payNow: "Şimdi Öde",
  processing: "İşleniyor...",
  paymentSuccess: "Ödeme başarılı!",
  paymentFailed: "Ödeme başarısız",
  tryAgain: "Tekrar dene",
  backToMenu: "Menüye dön",
  orderConfirmed: "Sipariş onaylandı!",
  orderNumber: "Sipariş Numarası",
  estimatedTime: "Tahmini Süre",
  trackOrder: "Siparişi Takip Et",
  pickupAddress: "Teslim Alma Adresi",
  deliveryOption: "Teslimat",
  pickupOption: "Gel Al",
  idealPayment: "iDEAL",
  cardPayment: "Kredi Kartı",
  cashPayment: "Teslimatta Nakit",
  invalidPostalCode: "Geçersiz posta kodu",
  denHaagOnly: "Sadece Den Haag'a teslimat yapıyoruz",
  requiredField: "Bu alan zorunludur",
  invalidEmail: "Geçersiz e-posta adresi",
  invalidPhone: "Geçersiz telefon numarası",
  minOrderAmount: "Minimum sipariş: €15",
  freeDeliveryFrom: "€35'den itibaren ücretsiz teslimat",
  staffConsole: "Personel Konsolu",
  greekIriniPremium: "Greek Irini Premium",
  liveLink: "Canlı Bağlantı Aktif",
  liveOrders: "Canlı Siparişler",
  history: "Geçmiş",
  reservations: "Rezervasyonlar",
  analytics: "Analitik",
  menuManagement: "Menü Yönetimi",
  settings: "Ayarlar",
  periodicReport: "Periyodik Rapor",
  financialInsight: "Finansal Görünüm",
  serviceQueue: "Servis Kuyruğu",
  activeRequests: "Aktif Talepler",
  searchOrders: "Sipariş ara...",
  noOrdersFound: "Bu görünüm için sipariş bulunamadı.",
  pendingReservations: "Bekleyen Rezervasyonlar",
  noPendingReservations: "Bekleyen rezervasyon yok",
  date: "Tarih",
  time: "Saat",
  guests: "Misafirler",
  phone: "Telefon",
  specialRequests: "Özel İstekler",
  adminNotes: "Onay için notlar",
  adminNotesPlaceholder: "Örn. pencere kenarı masa ayırtıldı...",
  confirmAndSendEmail: "Onayla ve E-posta Gönder",
  rejectReservation: "Rezervasyonu Reddet",
  close: "Kapat",
  reservationStatus: {
    pending: "Beklemede",
    confirmed: "Onaylandı",
    rejected: "Reddedildi",
    cancelled: "İptal Edildi"
  },
  confirmed: "onaylandı",
  pending: "beklemede",
  persons: "kişi",
  reservationsFor: "Rezervasyonlar",
  noReservationsThisDay: "Bu gün için rezervasyon yok",
  totalGuests: "Toplam misafir",
  confirmedRes: "Onaylandı",
  pendingRes: "Beklemede",
  confirmationSentAt: "Onay gönderildi",
  weekDays: ['Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt', 'Paz'],
  home: "Ana Sayfa",
  reservationNav: "Rezervasyon",
  revenueByCategory: "Kategoriye Göre Gelir",
  topBestsellers: "En Çok Satanlar Top 5",
  revenue: "Gelir",
  totalOrders: "Toplam Sipariş",
  avgOrderValue: "Ort. Sipariş Değeri",
  dishesSold: "Satılan Yemekler",
  peakHours: "Yoğun Saatler",
  hourlyOrders: "Saatlik Siparişler",
  revenueOverTime: "Zamana Göre Gelir",
  categoryBreakdown: "Kategori Dağılımı",
  deliveryStats: "Teslimat İstatistikleri",
  paymentMethods: "Ödeme Yöntemleri",
  weekdayTrends: "Hafta İçi Eğilimleri",
  addNewItem: "Yeni Ürün Ekle",
  editItem: "Ürünü Düzenle",
  deleteItem: "Ürünü Sil",
  available: "Mevcut",
  unavailable: "Mevcut Değil",
  units: "Adet",
  heroTitle: "Otantik Yunan Lezzeti",
  heroSub: "Ailemizden masanıza. Lahey'de Greek Irini'de Yunanistan'ın en iyilerini deneyimleyin.",
  orderNow: "Şimdi Sipariş Ver",
  ourMenu: "Menü",
  aboutUs: "Hakkımızda",
  contact: "İletişim",
  cart: "Sepet",
  total: "Toplam",
  addToCart: "Ekle",
  categories: { 
    mains: "Ana Yemekler", 
    starters_cold: "Soğuk Başlangıçlar", 
    starters_warm: "Sıcak Başlangıçlar", 
    salads: "Salatalar", 
    desserts: "Tatlılar" 
  },
  emptyCart: "Sepet boş",
  checkout: "Ödeme",
  contactTitle: "İletişime Geçin",
  contactSubtitle: "Sorularınız mı var? Yardımcı olmaktan mutluluk duyarız.",
  formName: "İsim",
  formEmail: "E-posta",
  formMessage: "Mesaj",
  formSubmit: "Gönder",
  writeReview: "Yorum Yaz"
};

const arAdmin = {
  adminDashboard: "لوحة الإدارة",
  activeOrders: "الطلبات النشطة",
  orderStatus: {
    pending: "قيد الانتظار",
    preparing: "قيد التحضير",
    ready: "جاهز",
    delivery: "قيد التوصيل",
    completed: "مكتمل",
    cancelled: "ملغي"
  },
  paymentStatus: {
    unpaid: "غير مدفوع",
    pending: "قيد المعالجة",
    paid: "مدفوع",
    failed: "فشل",
    refunded: "مسترد"
  },
  printReceipt: "طباعة الإيصال",
  deliveryAddress: "عنوان التوصيل",
  finishOrder: "إنهاء الطلب",
  checkoutTitle: "الدفع",
  deliveryDetails: "تفاصيل التوصيل",
  paymentMethod: "طريقة الدفع",
  orderSummary: "ملخص الطلب",
  subtotal: "المجموع الفرعي",
  deliveryFee: "رسوم التوصيل",
  totalToPay: "المجموع الكلي",
  payNow: "ادفع الآن",
  processing: "جاري المعالجة...",
  paymentSuccess: "تمت الدفع بنجاح!",
  paymentFailed: "فشل الدفع",
  tryAgain: "حاول مرة أخرى",
  backToMenu: "العودة إلى القائمة",
  orderConfirmed: "تم تأكيد الطلب!",
  orderNumber: "رقم الطلب",
  estimatedTime: "الوقت المقدر",
  trackOrder: "تتبع الطلب",
  pickupAddress: "عنوان الاستلام",
  deliveryOption: "التوصيل",
  pickupOption: "الاستلام",
  idealPayment: "iDEAL",
  cardPayment: "بطاقة ائتمان",
  cashPayment: "الدفع نقدًا عند التسليم",
  invalidPostalCode: "الرمز البريدي غير صالح",
  denHaagOnly: "نقوم بالتوصيل فقط في لاهاي",
  requiredField: "هذا الحقل مطلوب",
  invalidEmail: "عنوان البريد الإلكتروني غير صالح",
  invalidPhone: "رقم الهاتف غير صالح",
  minOrderAmount: "الحد الأدنى للطلب: €15",
  freeDeliveryFrom: "توصيل مجاني من €35",
  staffConsole: "لوحة الموظفين",
  greekIriniPremium: "Greek Irini Premium",
  liveLink: "الرابط المباشر نشط",
  liveOrders: "الطلبات المباشرة",
  history: "السجل",
  reservations: "الحجوزات",
  analytics: "التحليلات",
  menuManagement: "إدارة القائمة",
  settings: "الإعدادات",
  periodicReport: "تقرير دوري",
  financialInsight: "رؤية مالية",
  serviceQueue: "قائمة انتظار الخدمة",
  activeRequests: "الطلبات النشطة",
  searchOrders: "البحث عن الطلبات...",
  noOrdersFound: "لم يتم العثور على طلبات لهذا العرض.",
  pendingReservations: "الحجوزات المعلقة",
  noPendingReservations: "لا توجد حجوزات معلقة",
  date: "التاريخ",
  time: "الوقت",
  guests: "الضيوف",
  phone: "الهاتف",
  specialRequests: "طلبات خاصة",
  adminNotes: "ملاحظات للتأكيد",
  adminNotesPlaceholder: "مثل: حجز طاولة بجانب النافذة...",
  confirmAndSendEmail: "تأكيد وإرسال بريد إلكتروني",
  rejectReservation: "رفض الحجز",
  close: "إغلاق",
  reservationStatus: {
    pending: "قيد الانتظار",
    confirmed: "مؤكد",
    rejected: "مرفوض",
    cancelled: "ملغي"
  },
  confirmed: "مؤكد",
  pending: "قيد الانتظار",
  persons: "أشخاص",
  reservationsFor: "حجوزات لـ",
  noReservationsThisDay: "لا توجد حجوزات في هذا اليوم",
  totalGuests: "إجمالي الضيوف",
  confirmedRes: "مؤكد",
  pendingRes: "قيد الانتظار",
  confirmationSentAt: "تم إرسال التأكيد في",
  weekDays: ['الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت', 'الأحد'],
  home: "الرئيسية",
  reservationNav: "حجز",
  revenueByCategory: "الإيرادات حسب الفئة",
  topBestsellers: "أفضل 5 مبيعات",
  revenue: "الإيرادات",
  totalOrders: "إجمالي الطلبات",
  avgOrderValue: "متوسط قيمة الطلب",
  dishesSold: "الأطباق المباعة",
  peakHours: "ساعات الذروة",
  hourlyOrders: "الطلبات في الساعة",
  revenueOverTime: "الإيرادات مع الوقت",
  categoryBreakdown: "تصنيف الفئات",
  deliveryStats: "إحصائيات التوصيل",
  paymentMethods: "طرق الدفع",
  weekdayTrends: "اتجاهات أيام الأسبوع",
  addNewItem: "إضافة منتج جديد",
  editItem: "تعديل المنتج",
  deleteItem: "حذف المنتج",
  available: "متاح",
  unavailable: "غير متاح",
  units: "وحدات",
  heroTitle: "النكهة اليونانية الأصيلة",
  heroSub: "من عائلتنا إلى طاولتك. استمتع بأفضل ما في اليونان في لاهاي.",
  orderNow: "اطلب الآن",
  ourMenu: "القائمة",
  aboutUs: "من نحن",
  contact: "اتصل",
  cart: "السلة",
  total: "المجموع",
  addToCart: "إضافة",
  categories: { 
    mains: "الأطباق الرئيسية", 
    starters_cold: "مقبلات باردة", 
    starters_warm: "مقبلات ساخنة", 
    salads: "سلطات", 
    desserts: "حلويات" 
  },
  emptyCart: "السلة فارغة",
  checkout: "الدفع",
  contactTitle: "تواصل معنا",
  contactSubtitle: "لديك أسئلة؟ يسعدنا المساعدة.",
  formName: "الاسم",
  formEmail: "البريد الإلكتروني",
  formMessage: "الرسالة",
  formSubmit: "إرسال",
  writeReview: "اكتب تعليق"
};

const bgAdmin = {
  adminDashboard: "Админ Панел",
  activeOrders: "Активни Поръчки",
  orderStatus: {
    pending: "В Изчакване",
    preparing: "В Готвене",
    ready: "Готово",
    delivery: "На Доставка",
    completed: "Завършено",
    cancelled: "Отменено"
  },
  paymentStatus: {
    unpaid: "Неплатено",
    pending: "Обработва се",
    paid: "Платено",
    failed: "Неуспешно",
    refunded: "Възстановено"
  },
  printReceipt: "Принтирай Касова Бележка",
  deliveryAddress: "Адрес за Доставка",
  finishOrder: "Завърши Поръчка",
  checkoutTitle: "Плащане",
  deliveryDetails: "Детайли за Доставка",
  paymentMethod: "Метод на Плащане",
  orderSummary: "Обобщение на Поръчката",
  subtotal: "Междинна Сума",
  deliveryFee: "Цена за Доставка",
  totalToPay: "Обща Сума",
  payNow: "Плати Сега",
  processing: "Обработва се...",
  paymentSuccess: "Плащането е успешно!",
  paymentFailed: "Плащането е неуспешно",
  tryAgain: "Опитай отново",
  backToMenu: "Обратно към менюто",
  orderConfirmed: "Поръчката е потвърдена!",
  orderNumber: "Номер на Поръчка",
  estimatedTime: "Очаквано Време",
  trackOrder: "Проследи Поръчката",
  pickupAddress: "Адрес за Вземане",
  deliveryOption: "Доставка",
  pickupOption: "Вземане",
  idealPayment: "iDEAL",
  cardPayment: "Кредитна Карта",
  cashPayment: "В брой при доставка",
  invalidPostalCode: "Невалиден пощенски код",
  denHaagOnly: "Доставяме само в Хага",
  requiredField: "Това поле е задължително",
  invalidEmail: "Невалиден имейл адрес",
  invalidPhone: "Невалиден телефонен номер",
  minOrderAmount: "Минимална поръчка: €15",
  freeDeliveryFrom: "Безплатна доставка от €35",
  staffConsole: "Конзола за Персонал",
  greekIriniPremium: "Greek Irini Premium",
  liveLink: "Активна Връзка",
  liveOrders: "Текущи Поръчки",
  history: "История",
  reservations: "Резервации",
  analytics: "Аналитика",
  menuManagement: "Управление на Меню",
  settings: "Настройки",
  periodicReport: "Периодичен Доклад",
  financialInsight: "Финансов Преглед",
  serviceQueue: "Опашка за Обслужване",
  activeRequests: "Активни Заявки",
  searchOrders: "Търсене на поръчки...",
  noOrdersFound: "Не са намерени поръчки за този изглед.",
  pendingReservations: "Чакащи Резервации",
  noPendingReservations: "Няма чакащи резервации",
  date: "Дата",
  time: "Час",
  guests: "Гости",
  phone: "Телефон",
  specialRequests: "Специални Изисквания",
  adminNotes: "Бележки за потвърждение",
  adminNotesPlaceholder: "Напр. резервирана маса до прозореца...",
  confirmAndSendEmail: "Потвърди и Изпрати Имейл",
  rejectReservation: "Откажи Резервация",
  close: "Затвори",
  reservationStatus: {
    pending: "В Изчакване",
    confirmed: "Потвърдена",
    rejected: "Отказана",
    cancelled: "Отменена"
  },
  confirmed: "потвърдена",
  pending: "в изчакване",
  persons: "души",
  reservationsFor: "Резервации за",
  noReservationsThisDay: "Няма резервации за този ден",
  totalGuests: "Общо гости",
  confirmedRes: "Потвърдени",
  pendingRes: "В Изчакване",
  confirmationSentAt: "Потвърждение изпратено на",
  weekDays: ['Пон', 'Вто', 'Сря', 'Чет', 'Пет', 'Съб', 'Нед'],
  home: "Начало",
  reservationNav: "Резервация",
  revenueByCategory: "Приходи по Категория",
  topBestsellers: "Топ 5 Бестселъри",
  revenue: "Приходи",
  totalOrders: "Общо Поръчки",
  avgOrderValue: "Средна Стойност на Поръчка",
  dishesSold: "Продадени Ястия",
  peakHours: "Пикови Часове",
  hourlyOrders: "Поръчки на Час",
  revenueOverTime: "Приходи във Времето",
  categoryBreakdown: "Разбивка по Категории",
  deliveryStats: "Статистика за Доставки",
  paymentMethods: "Методи на Плащане",
  weekdayTrends: "Тенденции по Дни",
  addNewItem: "Добави Нов Артикул",
  editItem: "Редактирай Артикул",
  deleteItem: "Изтрий Артикул",
  available: "Наличен",
  unavailable: "Неналичен",
  units: "Броя",
  heroTitle: "Автентичен Гръцки Вкус",
  heroSub: "От нашето семейство до вашата маса. Насладете се на най-доброто от Гърция в Хага.",
  orderNow: "Поръчай Сега",
  ourMenu: "Меню",
  aboutUs: "За Нас",
  contact: "Контакт",
  cart: "Количка",
  total: "Общо",
  addToCart: "Добави",
  categories: { 
    mains: "Основни ястия", 
    starters_cold: "Студени предястия", 
    starters_warm: "Топли предястия", 
    salads: "Салати", 
    desserts: "Десерти" 
  },
  emptyCart: "Количката е празна",
  checkout: "Плащане",
  contactTitle: "Свържете се",
  contactSubtitle: "Имате въпроси? Ще се радваме да помогнем.",
  formName: "Име",
  formEmail: "Имейл",
  formMessage: "Съобщение",
  formSubmit: "Изпрати",
  writeReview: "Напишете отзив"
};

const plAdmin = {
  adminDashboard: "Panel Administratora",
  activeOrders: "Aktywne Zamówienia",
  orderStatus: {
    pending: "Oczekujące",
    preparing: "W kuchni",
    ready: "Gotowe",
    delivery: "W dostawie",
    completed: "Zakończone",
    cancelled: "Anulowane"
  },
  paymentStatus: {
    unpaid: "Nieopłacone",
    pending: "Przetwarzanie",
    paid: "Opłacone",
    failed: "Nieudane",
    refunded: "Zwrócone"
  },
  printReceipt: "Drukuj Paragon",
  deliveryAddress: "Adres Dostawy",
  finishOrder: "Zakończ Zamówienie",
  // Checkout translations PL
  checkoutTitle: "Zamówienie",
  deliveryDetails: "Dane dostawy",
  paymentMethod: "Metoda płatności",
  orderSummary: "Podsumowanie",
  subtotal: "Produkty",
  deliveryFee: "Dostawa",
  totalToPay: "Do zapłaty",
  payNow: "Zapłać teraz",
  processing: "Przetwarzanie...",
  paymentSuccess: "Płatność udana!",
  paymentFailed: "Płatność nieudana",
  tryAgain: "Spróbuj ponownie",
  backToMenu: "Powrót do menu",
  orderConfirmed: "Zamówienie potwierdzone!",
  orderNumber: "Numer zamówienia",
  estimatedTime: "Szacowany czas",
  trackOrder: "Śledź zamówienie",
  pickupAddress: "Adres odbioru",
  deliveryOption: "Dostawa",
  pickupOption: "Odbiór osobisty",
  idealPayment: "iDEAL",
  cardPayment: "Karta płatnicza",
  cashPayment: "Gotówka przy odbiorze",
  invalidPostalCode: "Nieprawidłowy kod pocztowy",
  denHaagOnly: "Dostarczamy tylko w Den Haag",
  requiredField: "To pole jest wymagane",
  invalidEmail: "Nieprawidłowy adres e-mail",
  invalidPhone: "Nieprawidłowy numer telefonu",
  minOrderAmount: "Minimalne zamówienie: €15",
  freeDeliveryFrom: "Darmowa dostawa od €35",
  // Admin panel navigation
  staffConsole: "Konsola personelu",
  greekIriniPremium: "Grecka Irini Premium",
  liveLink: "Aktywny link na żywo",
  liveOrders: "Zamówienia na żywo",
  history: "Historia",
  reservations: "Rezerwacje",
  analytics: "Analityka",
  menuManagement: "Zarządzanie menu",
  settings: "Ustawienia",
  periodicReport: "Raport okresowy",
  financialInsight: "Wgląd finansowy",
  // Orders
  serviceQueue: "Kolejka serwisowa",
  activeRequests: "Aktywnych żądań",
  searchOrders: "Wyszukaj zamówienia...",
  noOrdersFound: "Nie znaleziono zamówień dla tego widoku.",
  // Reservations
  pendingReservations: "Oczekujące Rezerwacje",
  noPendingReservations: "Brak oczekujących rezerwacji",
  date: "Data",
  time: "Godzina",
  guests: "Liczba Gości",
  phone: "Telefon",
  specialRequests: "Specjalne Życzenia",
  adminNotes: "Notatki do potwierdzenia",
  adminNotesPlaceholder: "Np. stolik przy oknie zarezerwowany...",
  confirmAndSendEmail: "Potwierdź i Wyślij Email",
  rejectReservation: "Odrzuć Rezerwację",
  close: "Zamknij",
  reservationStatus: {
    pending: "Oczekująca",
    confirmed: "Potwierdzona",
    rejected: "Odrzucona",
    cancelled: "Anulowana"
  },
  confirmed: "potwierdzone",
  pending: "oczekujące",
  persons: "os.",
  reservationsFor: "Rezerwacje na",
  noReservationsThisDay: "Brak rezerwacji na ten dzień",
  totalGuests: "Łącznie gości",
  confirmedRes: "Potwierdzone",
  pendingRes: "Oczekujące",
  confirmationSentAt: "Potwierdzenie wysłane",
  weekDays: ['Pon', 'Wt', 'Śr', 'Czw', 'Pt', 'Sob', 'Nd'],
  home: "Dom",
  reservationNav: "Rezerwacja",
  // Analytics
  revenueByCategory: "Przychody według Kategorii",
  topBestsellers: "Top 5 Bestsellerów",
  revenue: "Przychód",
  totalOrders: "Wszystkie Zamówienia",
  avgOrderValue: "Śr. Wartość Zamówienia",
  dishesSold: "Sprzedanych Dań",
  peakHours: "Godziny Szczytu",
  hourlyOrders: "Zamówienia na Godzinę",
  revenueOverTime: "Przychód w Czasie",
  categoryBreakdown: "Podział Kategorii",
  deliveryStats: "Statystyki Dostaw",
  paymentMethods: "Metody Płatności",
  weekdayTrends: "Trendy Dni Tygodnia",
  // Menu management
  addNewItem: "Dodaj Nowy Produkt",
  editItem: "Edytuj Produkt",
  deleteItem: "Usuń Produkt",
  available: "Dostępny",
  unavailable: "Niedostępny",
  units: "Sztuk"
};

export const TRANSLATIONS: Record<Language, TranslationSet> = {
  nl: {
    ...adminCommon,
    heroTitle: "Authentieke Griekse Smaak",
    heroSub: "Van onze familie tot aan uw tafel. Ervaar het beste van Griekenland bij Greek Irini in Den Haag.",
    orderNow: "Bestel Nu",
    ourMenu: "Menu",
    aboutUs: "Over Ons",
    contact: "Contact",
    cart: "Mandje",
    total: "Totaal",
    addToCart: "Toevoegen",
    categories: { 
      mains: "Hoofdgerechten", 
      starters_cold: "Koude Mezes", 
      starters_warm: "Warme Mezes", 
      salads: "Salades", 
      desserts: "Desserts" 
    },
    emptyCart: "Je mandje is leeg",
    checkout: "Afrekenen",
    authenticTitle: "Autentieke Smaken",
    authenticDesc: "Laat u verrassen door de authentieke smaken van Greek Irini en geniet van een stukje Griekenland in Den Haag.",
    bestsellers: "Bestsellers",
    familyBusiness: "Familiebedrijf",
    freshIngredients: "Verse Producten",
    reviews: "Klantbeoordelingen",
    contactTitle: "Contact opnemen",
    contactSubtitle: "Vragen? Wij staan voor u klaar.",
    formName: "Naam",
    formEmail: "Email",
    formMessage: "Bericht",
    formSubmit: "Versturen",
    location: "Locatie",
    openingHours: "Openingstijden",
    writeReview: "Schrijf een review",
    googleRating: "Google Waardering",
    aboutHeroTitle: "Een Erfenis van Smaak",
    aboutHeroSub: "Het verhaal van Greek Irini begon aan de kusten van de Egeïsche Zee en bloeit nu in het hart van Den Haag.",
    ourStoryTitle: "Onze Reis",
    ourStoryText: "Greek Irini is meer dan een restaurant; het is een stukje Griekse ziel in de Weimarstraat. Opgericht met een visie om de oprechte gastvrijheid (Philoxenia) naar Nederland te brengen.",
    philosophyTitle: "Onze Filosofie",
    philosophySub: "De Drie Pijlers van Irini",
    philosophyText: "Wij geloven dat eten een cultuur is. Onze olijfolie komt rechtstreeks van onze eigen boomgaarden.",
    philosophyPillar1Title: "De Bodem",
    philosophyPillar1Text: "De puurste olijfolie uit eigen boomgaarden.",
    philosophyPillar2Title: "De Haard",
    philosophyPillar2Text: "Traditionele technieken ontmoeten moderne precisie.",
    philosophyPillar3Title: "De Tafel",
    philosophyPillar3Text: "Philoxenia - de kunst van gastvrijheid.",
    teamTitle: "De Irini Familie",
    teamSub: "De mensen achter de passie.",
    founderLabel: "Oprichter & Ziel",
    chefLabel: "Executive Chef",
    serviceLabel: "Gastheer"
  },
  pl: {
    ...plAdmin,
    heroTitle: "Autentyczny Grecki Smak",
    heroSub: "Od naszej rodziny na Twój stół. Doświadcz najlepszych smaków Grecji w Hadze u Greek Irini.",
    orderNow: "Zamów Teraz",
    ourMenu: "Menu",
    aboutUs: "O Nas",
    contact: "Kontakt",
    cart: "Koszyk",
    total: "Suma",
    addToCart: "Dodaj",
    categories: { 
      mains: "Dania Główne", 
      starters_cold: "Zimne Przystawki", 
      starters_warm: "Ciepłe Przystawki", 
      salads: "Sałatki", 
      desserts: "Desery" 
    },
    emptyCart: "Koszyk jest pusty",
    checkout: "Płać i Zamów",
    authenticTitle: "Autentyczne Smaki",
    authenticDesc: "Daj się zaskoczyć autentycznym smakom Greek Irini i rozkoszuj się kawałkiem Grecji w Hadze.",
    bestsellers: "Bestsellery",
    familyBusiness: "Rodzinny Biznes",
    freshIngredients: "Świeże Produkty",
    reviews: "Opinie",
    contactTitle: "Skontaktuj się",
    contactSubtitle: "Masz pytania? Chętnie pomożemy.",
    formName: "Imię",
    formEmail: "E-mail",
    formMessage: "Wiadomość",
    formSubmit: "Wyślij",
    location: "Lokalizacja",
    openingHours: "Godziny Otwarcia",
    writeReview: "Zostaw opinię",
    googleRating: "Ocena Google",
    aboutHeroTitle: "Dziedzictwo Smaku",
    aboutHeroSub: "Historia Greek Irini zaczęła się na wybrzeżach Morza Egejskiego, a dziś rozkwita w sercu Hagi.",
    ourStoryTitle: "Nasza Podróż",
    ourStoryText: "Greek Irini to więcej niż restauracja; to kawałek greckiej duszy przy Weimarstraat. Założona z wizją przeniesienia szczerej gościnności (Philoxenia) do Holandii.",
    philosophyTitle: "Nasza Filozofia",
    philosophySub: "Trzy Filary Irini",
    philosophyText: "Wierzymy, że jedzenie to kultura. Nasza oliwa pochodzi prosto z naszych własnych gajów.",
    philosophyPillar1Title: "Ziemia",
    philosophyPillar1Text: "Najczystsza oliwa z własnych gajów.",
    philosophyPillar2Title: "Ogień",
    philosophyPillar2Text: "Tradycyjne techniki połączone z nowoczesną precyzją.",
    philosophyPillar3Title: "Stół",
    philosophyPillar3Text: "Philoxenia - sztuka czynienia przyjaciela.",
    teamTitle: "Rodzina Irini",
    teamSub: "Ludzie, którzy tworzą pasję.",
    founderLabel: "Założycielka",
    chefLabel: "Szef Kuchni",
    serviceLabel: "Manager"
  },
  el: { 
    ...elAdmin,
    authenticTitle: "Αυθεντικές Γεύσεις",
    authenticDesc: "Ανακαλύψτε τις αυθεντικές γεύσεις του Greek Irini και απολαύστε ένα κομμάτι της Ελλάδας στη Χάγη.",
    bestsellers: "Μπεστ Σέλερ",
    familyBusiness: "Οικογενειακή Επιχείρηση",
    freshIngredients: "Φρέσκα Προϊόντα",
    reviews: "Κριτικές",
    location: "Τοποθεσία",
    openingHours: "Ώρες Λειτουργίας",
    googleRating: "Αξιολόγηση Google",
    aboutHeroTitle: "Μια Κληρονομιά Γεύσης",
    aboutHeroSub: "Η ιστορία του Greek Irini ξεκίνησε στις ακτές του Αιγαίου και ανθίζει τώρα στην καρδιά της Χάγης.",
    ourStoryTitle: "Το Ταξίδι Μας",
    ourStoryText: "Το Greek Irini είναι περισσότερο από ένα εστιατόριο· είναι ένα κομμάτι της ελληνικής ψυχής στο Weimarstraat. Ιδρύθηκε με το όραμα να φέρει την αληθινή φιλοξενία (Philoxenia) στην Ολλανδία.",
    philosophyTitle: "Η Φιλοσοφία Μας",
    philosophySub: "Οι Τρεις Πυλώνες της Irini",
    philosophyText: "Πιστεύουμε ότι το φαγητό είναι πολιτισμός. Το λάδι μας προέρχεται απευθείας από τους δικούς μας ελαιώνες.",
    philosophyPillar1Title: "Η Γη",
    philosophyPillar1Text: "Το πιο καθαρό λάδι από τους δικούς μας ελαιώνες.",
    philosophyPillar2Title: "Η Φωτιά",
    philosophyPillar2Text: "Παραδοσιακές τεχνικές με σύγχρονη ακρίβεια.",
    philosophyPillar3Title: "Το Τραπέζι",
    philosophyPillar3Text: "Philoxenia - η τέχνη της φιλοξενίας.",
    teamTitle: "Η Οικογένεια Irini",
    teamSub: "Οι άνθρωποι πίσω από το πάθος.",
    founderLabel: "Ιδρυτής",
    chefLabel: "Σεφ",
    serviceLabel: "Διευθυντής"
  } as any,
  tr: { 
    ...trAdmin,
    authenticTitle: "Otantik Tatlar",
    authenticDesc: "Greek Irini'nin otantik tatlarını keşfedin ve Lahey'de Yunanistan'ın bir parçasını tadın.",
    bestsellers: "En Çok Satanlar",
    familyBusiness: "Aile İşletmesi",
    freshIngredients: "Taze Ürünler",
    reviews: "Yorumlar",
    location: "Konum",
    openingHours: "Açılış Saatleri",
    googleRating: "Google Değerlendirmesi",
    aboutHeroTitle: "Lezzet Mirası",
    aboutHeroSub: "Greek Irini'nin hikayesi Ege kıyılarında başladı ve şimdi Lahey'in kalbinde çiçek açıyor.",
    ourStoryTitle: "Yolculuğumuz",
    ourStoryText: "Greek Irini bir restorandan fazlası; Weimarstraat'ta Yunan ruhunun bir parçası. Gerçek misafirperverliği (Philoxenia) Hollanda'ya getirme vizyonuyla kuruldu.",
    philosophyTitle: "Felsefemiz",
    philosophySub: "Irini'nin Üç Sütunu",
    philosophyText: "Yemeğin bir kültür olduğuna inanıyoruz. Zeytinyağımız kendi zeytinliklerimizden geliyor.",
    philosophyPillar1Title: "Toprak",
    philosophyPillar1Text: "Kendi zeytinliklerimizden en saf zeytinyağı.",
    philosophyPillar2Title: "Ateş",
    philosophyPillar2Text: "Geleneksel teknikler modern hassasiyetle buluşuyor.",
    philosophyPillar3Title: "Masa",
    philosophyPillar3Text: "Philoxenia - misafirperverlik sanatı.",
    teamTitle: "Irini Ailesi",
    teamSub: "Tutkumuzun arkasındaki insanlar.",
    founderLabel: "Kurucu",
    chefLabel: "Şef",
    serviceLabel: "Müdür"
  } as any,
  ar: { 
    ...arAdmin,
    authenticTitle: "النكهات الأصيلة",
    authenticDesc: "اكتشف النكهات الأصيلة لـ Greek Irini واستمتع بقطعة من اليونان في لاهاي.",
    bestsellers: "الأكثر مبيعًا",
    familyBusiness: "عمل عائلي",
    freshIngredients: "مكونات طازجة",
    reviews: "التقييمات",
    location: "الموقع",
    openingHours: "ساعات العمل",
    googleRating: "تقييم جوجل",
    aboutHeroTitle: "إرث من النكهة",
    aboutHeroSub: "بدأت قصة Greek Irini على شواطئ بحر إيجه وتزدهر الآن في قلب لاهاي.",
    ourStoryTitle: "رحلتنا",
    ourStoryText: "Greek Irini أكثر من مجرد مطعم؛ إنه قطعة من الروح اليونانية في Weimarstraat. تأسست برؤية لجلب الضيافة الحقيقية (Philoxenia) إلى هولندا.",
    philosophyTitle: "فلسفتنا",
    philosophySub: "الأعمدة الثلاثة لـ Irini",
    philosophyText: "نؤمن بأن الطعام ثقافة. زيتنا يأتي مباشرة من بساتيننا الخاصة.",
    philosophyPillar1Title: "الأرض",
    philosophyPillar1Text: "أنقى زيت الزيتون من بساتيننا الخاصة.",
    philosophyPillar2Title: "النار",
    philosophyPillar2Text: "تقنيات تقليدية تلتقي بالدقة الحديثة.",
    philosophyPillar3Title: "المائدة",
    philosophyPillar3Text: "Philoxenia - فن الضيافة.",
    teamTitle: "عائلة Irini",
    teamSub: "الأشخاص وراء الشغف.",
    founderLabel: "المؤسس",
    chefLabel: "الشيف",
    serviceLabel: "المدير"
  } as any,
  bg: { 
    ...bgAdmin,
    authenticTitle: "Автентични Вкусове",
    authenticDesc: "Открийте автентичните вкусове на Greek Irini и се насладете на парче от Гърция в Хага.",
    bestsellers: "Бестселъри",
    familyBusiness: "Семеен Бизнес",
    freshIngredients: "Пресни Продукти",
    reviews: "Отзиви",
    location: "Местоположение",
    openingHours: "Работно Време",
    googleRating: "Google Рейтинг",
    aboutHeroTitle: "Наследство на Вкуса",
    aboutHeroSub: "Историята на Greek Irini започна на бреговете на Егейско море и сега цъфти в сърцето на Хага.",
    ourStoryTitle: "Нашето Пътуване",
    ourStoryText: "Greek Irini е повече от ресторант; това е парче от гръцката душа на Weimarstraat. Основан с визия да донесе истинското гостоприемство (Philoxenia) в Холандия.",
    philosophyTitle: "Нашата Философия",
    philosophySub: "Трите Стълба на Irini",
    philosophyText: "Вярваме, че храната е култура. Маслото ни идва директно от собствените ни маслинови горички.",
    philosophyPillar1Title: "Земята",
    philosophyPillar1Text: "Най-чистото зехтин от собствените ни горички.",
    philosophyPillar2Title: "Огънят",
    philosophyPillar2Text: "Традиционни техники срещат модерна прецизност.",
    philosophyPillar3Title: "Масата",
    philosophyPillar3Text: "Philoxenia - изкуството на гостоприемството.",
    teamTitle: "Семейство Irini",
    teamSub: "Хората зад страстта.",
    founderLabel: "Основател",
    chefLabel: "Готвач",
    serviceLabel: "Мениджър"
  } as any,
};

export const MENU_ITEMS: MenuItem[] = [
  // --- MAINS ---
  {
    id: 'm1', category: 'mains', price: 26.00,
    image: '/Lamskoteletten.png',
    names: { pl: 'Kotlety jagnięce', nl: 'Lamskoteletten', el: 'Παιδάκια', tr: 'Kuzu Pirzola', ar: 'ريش غنم', bg: 'Агнешки котлети' },
    descriptions: { pl: 'Soczyste kotlety z grilla z greckimi ziołami.', nl: 'Gegrilde lamskoteletten met Griekse kruiden.', el: 'Ψητά παϊδάκια με ελληνικά μυρωδικά.', tr: 'Yunan otları ile ızgara kuzu pirzola.', ar: 'ريش غنم مشوية بالأعشاب اليونانية.', bg: 'Агнешки котлети на скара.' }
  },
  {
    id: 'm2', category: 'mains', price: 24.00,
    image: '/mix.png',
    names: { pl: 'Mix Grill', nl: 'Mix Grill', el: 'Μιξ Γκριλ', tr: 'Karışık Izgara', ar: 'مشاوي مشكلة', bg: 'Микс Грил' },
    descriptions: { pl: 'Różnorodność najlepszych mięs z grilla.', nl: 'Variëteit aan de beste gegrilde vleessoorten.', el: 'Ποικιλία από τα καλύτερα ψητά κρέατα.', tr: 'En iyi ızgara etlerin çeşitliliği.', ar: 'تشكيلة من أفضل اللحوم المشوية.', bg: 'Разнообразие от naj-dobrite меса на скара.' }
  },
  {
    id: 'm3', category: 'mains', price: 9.00,
    image: '/Pita Gyros.png',
    names: { pl: 'Pita Gyros', nl: 'Pita Gyros', el: 'Πίτα Γύρος', tr: 'Pita Gyros', ar: 'بيتا جيروس', bg: 'Пита Гирос' },
    descriptions: { pl: 'Klasyczna pita z gyrosem, pomidorem i cebulą.', nl: 'Klassieke pita met gyros, tomaat en ui.', el: 'Κλασική πίτα με γύρο, ντομάτα και κρεμμύδι.', tr: 'Domates ve soğanlı klasik pita gyros.', ar: 'بيتا كلاسيكية مع جيروس وطماطم وبصل.', bg: 'Класическа пита с гирос, домати и лук.' }
  },
  {
    id: 'm4', category: 'mains', price: 20.00,
    image: '/Souvlaki Schotel.png',
    names: { pl: 'Souvlaki Dish', nl: 'Souvlaki Schotel', el: 'Πιάτο Σουβλάκι', tr: 'Souvlaki Tabağı', ar: 'طبق سوفلاكي', bg: 'Сувлаки плато' },
    descriptions: { pl: 'Szaszłyki z grilla podawane z frytkami i pitą.', nl: 'Gegrilde spiesen geserveerd met friet en pita.', el: 'Καλαμάκια στα κάρβουνα με πατάτες και πίτα.', tr: 'Patates kızartması ve pita ile servis edilen ızgara şişler.', ar: 'أسياخ مشوية تقدم مع البطاطس والبيتا.', bg: 'Шишчета на скара, поднесени с пържени картофи и пита.' }
  },
  {
    id: 'm5', category: 'mains', price: 18.00,
    image: '/Mussakka.png',
    names: { pl: 'Moussaka', nl: 'Moussaka', el: 'Μουσακάς', tr: 'Musakka', ar: 'مسقعة', bg: 'Мусака' },
    descriptions: { pl: 'Tradycyjna zapiekanka z bakłażanem i mięsem.', nl: 'Traditionele ovenschotel met aubergine en gehakt.', el: 'Παραδοσιακός μουσακάς με μελιτζάνες.', tr: 'Patlıcanlı geleneksel musakka.', ar: 'مسقعة تقليدية بالباذنجان واللحم.', bg: 'Традиционна мусака с патладжан и кайма.' }
  },
  {
    id: 'm6', category: 'mains', price: 20.00,
    image: '/mix.png',
    names: { pl: 'Bifteki Dish', nl: 'Bifteki Schotel', el: 'Μπιφτέκι', tr: 'Bifteki Tabağı', ar: 'طبق بيفتيكي', bg: 'Бифтеки плато' },
    descriptions: { pl: 'Greckie mielone nadziewane fetą.', nl: 'Grieks gehakt gevuld met feta.', el: 'Μπιφτέκι γεμιστό με φέτα.', tr: 'Feta peyniri ile doldurulmuş Yunan köftesi.', ar: 'كفتة يونانية محشوة بجبنة الفيتا.', bg: 'Гръцко кюфте, пълнено с фета.' }
  },
  {
    id: 'm7', category: 'mains', price: 25.00,
    image: '/Mix Seafood.png',
    names: { pl: 'Mix owoców morza', nl: 'Mix Zeevruchten', el: 'Ποικιλία Θαλασσινών', tr: 'Karışık Deniz Ürünleri', ar: 'فواكه بحر مشكلة', bg: 'Микс морски дарове' },
    descriptions: { pl: 'Świeże owoce morza prosto z grilla.', nl: 'Verse zeevruchten rechtstreeks van de grill.', el: 'Φρέσκα θαλασσινά στη σχάρα.', tr: 'Izgaradan taze deniz ürünleri.', ar: 'فواكه بحر طازجة من المشواة.', bg: 'Пресни морски дарове директно от скарата.' }
  },
  {
    id: 'm8', category: 'mains', price: 25.00,
    image: '/Ribeye Steak.png',
    names: { pl: 'Stek antrykotu', nl: 'Entrecote Steak', el: 'Σπαλομπριζόλα', tr: 'Antrikot Biftek', ar: 'ستيك أنتريكوت', bg: 'Стек Антрекот' },
    descriptions: { pl: 'Soczysty stek z antrykotu sezonowany greckimi ziołami.', nl: 'Sappige entrecote steak gekruid met Griekse kruiden.', el: 'Ζουμερή σπαλομπριζόλα με ελληνικά βότανα.', tr: 'Yunan otları ile tatlandırılmış sulu antrikot biftek.', ar: 'ستيك أنتريكوت سوسي متبل بالأعشاب اليونانية.', bg: 'Сочен стек от антрекот, овкусен с гръцки билки.' }
  },
  {
    id: 'm9', category: 'mains', price: 18.00,
    image: '/Gyros Schotel.png',
    names: { pl: 'Gyros Dish', nl: 'Gyros Schotel', el: 'Πιάτο Γύρος', tr: 'Gyros Tabağı', ar: 'طبق جيروس', bg: 'Плато Гирос' },
    descriptions: { pl: 'Porcja gyrosu podawana z dodatkami.', nl: 'Gyros portie geserveerd met bijgerechten.', el: 'Μερίδα γύρος με συνοδευτικά.', tr: 'Garnitürlerle servis edilen gyros porsiyonu.', ar: 'وجبة جيروس تقدم مع أطباق جانبية.', bg: 'Порция гирос, поднесена с гарнитури.' }
  },

  // --- COLD STARTERS ---
  {
    id: 'sc1', category: 'starters_cold', price: 6.00,
    image: '/Tzatziki.png',
    names: { pl: 'Tzatziki', nl: 'Tzatziki', el: 'Τζατζίκι', tr: 'Cacık', ar: 'تزاتزيكي', bg: 'Дзадзики' },
    descriptions: { pl: 'Jogurt grecki, ogórek, czosnek.', nl: 'Griekse yoghurt met knoflook en komkommer.', el: 'Γιαούρτι με σκόρδο και αγγούρι.', tr: 'Sarımsaklı ve salatalıklı yoğurt.', ar: 'زبادي يوناني بالثوم والخيار.', bg: 'Гръцко кисело мляко с чесън и краставица.' }
  },
  {
    id: 'sc2', category: 'starters_cold', price: 16.00,
    image: '/mix.png',
    names: { pl: 'Mix zimnych przystawek', nl: 'Mix Koude Voorgerechten', el: 'Ποικιλία Κρύων Ορεκτικών', tr: 'Karışık Soğuk Meze', ar: 'مقبلات باردة مشكلة', bg: 'Микс студени предястия' },
    descriptions: { pl: 'Wybór tradycyjnych greckich mezes.', nl: 'Selectie van traditionele Griekse mezes.', el: 'Επιλογή παραδοσιακών ελληνικών μεζέδων.', tr: 'Geleneksel Yunan mezeleri seçkisi.', ar: 'تشكيلة من المزة اليونانية التقليدية.', bg: 'Селекция от традиционни гръцки мезета.' }
  },
  {
    id: 'sc3', category: 'starters_cold', price: 5.00,
    image: '/Tzatziki.png',
    names: { pl: 'Feta', nl: 'Feta', el: 'Φέτα', tr: 'Feta Peyniri', ar: 'فيتا', bg: 'Фета' },
    descriptions: { pl: 'Oryginalna grecka feta z oliwą i oregano.', nl: 'Originele Griekse feta met olijfolie en oregano.', el: 'Αυθεντική φέτα με ελαιόλαδο και ρίγανη.', tr: 'Zeytinyağı ve kekikli orijinal Yunan fetası.', ar: 'جبنة فيتا يونانية أصلية بزيت الزيتون والزعتر.', bg: 'Оригинална гръцка фета със зехтин и риган.' }
  },
  {
    id: 'sc4', category: 'starters_cold', price: 4.00,
    image: '/Griekse Salad.png',
    names: { pl: 'Oliwki', nl: 'Olijven', el: 'Ελιές', tr: 'Zeytin', ar: 'زيتون', bg: 'Маслини' },
    descriptions: { pl: 'Greckie oliwki Kalamata.', nl: 'Griekse Kalamata olijven.', el: 'Ελληνικές ελιές Καλαμών.', tr: 'Yunan Kalamata zeytini.', ar: 'زيتون كالاماتا يوناني.', bg: 'Гръцки маслини Каламата.' }
  },
  {
    id: 'sc5', category: 'starters_cold', price: 12.00,
    image: '/Tzatziki.png',
    names: { pl: 'Trio (potrójny zestaw)', nl: 'Trio Dips', el: 'Τρίο Αλοιφών', tr: 'Üçlü Sos Seti', ar: 'مجموعة تريو', bg: 'Трио дипове' },
    descriptions: { pl: 'Zestaw trzech tradycyjnych past greckich.', nl: 'Set van drie traditionele Griekse dips.', el: 'Σετ από τρεις παραδοσιακές αλοιφές.', tr: 'Üç geleneksel Yunan ezmesi seti.', ar: 'مجموعة من ثلاث غموس يونانية تقليدية.', bg: 'Сет от три традиционни гръцки разядки.' }
  },
  {
    id: 'sc6', category: 'starters_cold', price: 6.00,
    image: '/Tarama.png',
    names: { pl: 'Tarama', nl: 'Tarama', el: 'Ταραμάς', tr: 'Tarama', ar: 'تاراما', bg: 'Тарама' },
    descriptions: { pl: 'Pasta z ikry rybiej.', nl: 'Dip van viskuit.', el: 'Αλοιφή από ταραμά.', tr: 'Balık yumurtası ezmesi.', ar: 'غموس بيض السمك.', bg: 'Разядка от хайвер.' }
  },

  // --- WARM STARTERS ---
  {
    id: 'sw1', category: 'starters_warm', price: 12.00,
    image: '/Papoutsaki.png',
    names: { pl: 'Papoutsaki', nl: 'Papoutsaki', el: 'Παπουτσάκι', tr: 'Papoutsaki', ar: 'بابوتساكي', bg: 'Папуцаки' },
    descriptions: { pl: 'Faszerowany bakłażan z beszamelem.', nl: 'Gevulde aubergine met bechamelsaus.', el: 'Μελιτζάνα γεμιστή με μπεσαμέλ.', tr: 'Beşamel soslu dolma patlıcan.', ar: 'باذنجان محشو بالبشاميل.', bg: 'Пълнен патладжан с бешамел.' }
  },
  {
    id: 'sw2', category: 'starters_warm', price: 18.00,
    image: '/Calamares.png',
    names: { pl: 'Kalmary', nl: 'Calamari', el: 'Καλαμαράκια', tr: 'Kalamar', ar: 'كاليماري', bg: 'Калмари' },
    descriptions: { pl: 'Smażone krążki kalmarów.', nl: 'Gefrituurde inktvisringen.', el: 'Τηγανητά καλαμαράκια.', tr: 'Kızarmış kalamar halkaları.', ar: 'حلقات كاليماري مقلية.', bg: 'Пържени кръгчета калмар.' }
  },
  {
    id: 'sw3', category: 'starters_warm', price: 12.00,
    image: '/Feta Sxaras.png',
    names: { pl: 'Feta Sxaras', nl: 'Gegrilde Feta', el: 'Φέτα Σχάρας', tr: 'Izgara Feta', ar: 'فيتا مشوية', bg: 'Фета на скара' },
    descriptions: { pl: 'Grillowana feta z pomidorem i papryką.', nl: 'Gegrilde feta met tomaat en paprika.', el: 'Φέτα στη σχάρα με ντομάτα και πιπεριά.', tr: 'Domates ve biberli ızgara feta.', ar: 'فيتا مشوية مع طماطم وفلفل.', bg: 'Фета на скара с домати и чушки.' }
  },
  {
    id: 'sw4', category: 'starters_warm', price: 3.00,
    image: '/Griekse Salad.png',
    names: { pl: 'Kafteres', nl: 'Kafteres', el: 'Καυτερές Πιπεριές', tr: 'Acı Biber', ar: 'فلفل حار', bg: 'Люти чушки' },
    descriptions: { pl: 'Pikantne grillowane papryczki.', nl: 'Pittige gegrilde pepers.', el: 'Καυτερές πιπεριές στη σχάρα.', tr: 'Baharatlı ızgara biberler.', ar: 'فلفل مشوي حار.', bg: 'Пикантни чушки на скара.' }
  },
  {
    id: 'sw5', category: 'starters_warm', price: 12.00,
    image: '/Kolokeftedes - Courgette.png',
    names: { pl: 'Kolokithokeftedes', nl: 'Zucchini Koekjes', el: 'Κολοκυθοκεφτέδες', tr: 'Kabak Mücveri', ar: 'أقراص الكوسة', bg: 'Тиκвени кюфтета' },
    descriptions: { pl: 'Greckie placki z cukinii i fety.', nl: 'Griekse courgettekoekjes met feta.', el: 'Κολοκυθοκεφτέδες με φέτα.', tr: 'Feta peynirli Yunan kabak mücveri.', ar: 'أقراص كوسة يونانية بجبنة الفيتا.', bg: 'Гръцки кюфтета от тиквички с фета.' }
  },
  {
    id: 'sw6', category: 'starters_warm', price: 16.00,
    image: '/mix.png',
    names: { pl: 'Mix ciepłych przystawek', nl: 'Mix Warme Voorgerechten', el: 'Ποικιλία Ζεστών Ορεκτικών', tr: 'Karışık Sıcak Meze', ar: 'مقبلات ساخنة مشكلة', bg: 'Микс топли предястия' },
    descriptions: { pl: 'Wybór najpopularniejszych gorących przystawek.', nl: 'Selectie van de populairste warme voorgerechten.', el: 'Επιλογή από τα πιο δημοφιλή ζεστά ορεκτικά.', tr: 'En popüler sıcak mezelerin seçkisi.', ar: 'تشكيلة من أشهر المقبلات الساخنة.', bg: 'Селекция от най-популярните топли предястия.' }
  },
  {
    id: 'sw7', category: 'starters_warm', price: 5.00,
    image: '/Skordopsomo.png',
    names: { pl: 'Skordopsomo', nl: 'Knoflookbrood', el: 'Σκορδόψωμο', tr: 'Sarımsaklı Ekmek', ar: 'خبza بالثوم', bg: 'Чеснов хляб' },
    descriptions: { pl: 'Chrupiący chleb czosnkowy z greckimi ziołami.', nl: 'Knapperig knoflookbrood met Griekse kruiden.', el: 'Τραγανό σκορδόψωμο με ελληνικά βότανα.', tr: 'Yunan otları ile çıtır sarımsaklı ekmek.', ar: 'خبز بالثوم مقرمش بالأعشاب اليونانية.', bg: 'Хрупкав чеснов хляб с гръцки билки.' }
  },
  {
    id: 'sw8', category: 'starters_warm', price: 16.00,
    image: '/Saganaki Garnalen.png',
    names: { pl: 'Krewetki Saganaki', nl: 'Garnalen Saganaki', el: 'Γαρίδες Σαγανάκι', tr: 'Karides Saganaki', ar: 'جمبري ساجاناكي', bg: 'Скариди Саганаки' },
    descriptions: { pl: 'Krewetki duszone w sosie pomidorowym z fetą.', nl: 'Garnalen gestoofd in tomatensaus met feta.', el: 'Γαρίδες σε σάλτσα ντομάτας με φέτα.', tr: 'Domates sosunda feta peynirli karides.', ar: 'جمبري مطهو في صلصة الطماطم مع الفيتا.', bg: 'Скариди, задушени в доматен сос с фета.' }
  },
  {
    id: 'sw9', category: 'starters_warm', price: 12.00,
    image: '/Mix Seafood.png',
    names: { pl: 'Ośmiornica', nl: 'Octopus', el: 'Χταπόδι', tr: 'Ahtapot', ar: 'أخطبوط', bg: 'Октопод' },
    descriptions: { pl: 'Grillowana ośmiornica podawana z octem i oliwą.', nl: 'Gegrilde octopus geserveerd met azijn en olie.', el: 'Χταπόδι στη σχάρα με ξύδι και λάδι.', tr: 'Sirke ve yağ ile servis edilen ızgara ahtapot.', ar: 'أخطبوط مشوي يقدم مع الخل والزيت.', bg: 'Октопод на скара, поднесен с оцет и зехтин.' }
  },

  // --- SALADS ---
  {
    id: 'sl1', category: 'salads', price: 14.00,
    image: '/Griekse Salad.png',
    names: { pl: 'Sałatka grecka', nl: 'Griekse Salade', el: 'Χωριάτικη Σαλάτα', tr: 'Yunan Salatası', ar: 'سلطة يونانية', bg: 'Гръцка салата' },
    descriptions: { pl: 'Pomidor, ogórek, cebula, feta i oliwki.', nl: 'Tomaat, komkommer, ui, feta en olijven.', el: 'Ντομάτα, αγγούρι, κρεμμύδι, φέτα και ελιές.', tr: 'Domates, salatalık, soğan, feta ve zeytin.', ar: 'طماطم وخيار وبصل وفيتا وزيتون.', bg: 'Домати, краставици, лук, фета и маслини.' }
  },
  {
    id: 'sl2', category: 'salads', price: 10.00,
    image: '/Salade Irini.png',
    names: { pl: 'Sałatka zielona', nl: 'Groene Salade', el: 'Πράσινη Σαλάτα', tr: 'Yeşil Salata', ar: 'سلطة خضراء', bg: 'Зелена салата' },
    descriptions: { pl: 'Mieszanka świeżych zielonych sałat z dressingiem.', nl: 'Mix van verse groene salades met dressing.', el: 'Ανάμεικτη πράσινη σαλάτα με ντρίσινγκ.', tr: 'Soslu taze yeşil salata karışımı.', ar: 'مزيج من السلطات الخضراء الطازجة مع التتبيلة.', bg: 'Микс от пресни зелени салати с дресинг.' }
  },
  {
    id: 'sl3', category: 'salads', price: 10.00,
    image: '/Koolsalad.png',
    names: { pl: 'Surówka z kapusty', nl: 'Koolsalade', el: 'Λαχανοσαλάτα', tr: 'Lahana Salatası', ar: 'سلطة ملفوف', bg: 'Зелева салата' },
    descriptions: { pl: 'Świeża, chrupiąca kapusta w greckim stylu.', nl: 'Verse, knapperige koolsalade in Griekse stijl.', el: 'Φρέσκια, τραγανή λαχανοσαλάτα.', tr: 'Yunan usulü taze çıtır lahana salatası.', ar: 'سلطة ملفوف طازجة ومقرمشة على الطريقة اليونانية.', bg: 'Прясна хрупкава зелева салата в гръцки стил.' }
  },
  {
    id: 'sl4', category: 'salads', price: 13.50,
    image: '/Salade Irini.png',
    names: { pl: 'Sałatka Irini', nl: 'Irini Salade', el: 'Σαλάτα Ειρήνη', tr: 'Irini Salatası', ar: 'سلطة إيريني', bg: 'Салата Ирини' },
    descriptions: { pl: 'Autorska sałatka z unikalnym dressingiem Irini.', nl: 'Handtekening salade met unieke Irini dressing.', el: 'Η σπεσιαλιτέ σαλάτα μας με ντρίσινγκ Ειρήνη.', tr: 'Eşsiz Irini soslu imza salata.', ar: 'سلطة مميزة مع تتبيلة إيريني الفريدة.', bg: 'Авторска салата с уникален дресинг Ирини.' }
  },

  // --- DESSERTS ---
  {
    id: 'd1', category: 'desserts', price: 7.00,
    image: '/Sokolatopita.png',
    names: { pl: 'Sokolatopita', nl: 'Chocoladetaart', el: 'Σοκολατόπιτα', tr: 'Çikolatalı Kek', ar: 'كعكة الشوكولاتة', bg: 'Шоколадов кейк' },
    descriptions: { pl: 'Tradycyjne greckie ciasto czekoladowe.', nl: 'Traditionele Griekse chocoladetaart.', el: 'Παραδοσιακή ελληνική σοκολατόπιτα.', tr: 'Geleneksel Yunan çikolatalı keki.', ar: 'كعكة شوكولاتة يونانية تقليدية.', bg: 'Традиционен гръцки шоколадов кейк.' }
  },
  {
    id: 'd2', category: 'desserts', price: 7.00,
    image: '/Portokalopita.png',
    names: { pl: 'Portokalopita', nl: 'Sinaasappeltaart', el: 'Πορτοκαλόπιτα', tr: 'Portakallı Kek', ar: 'كعكة البرتقال', bg: 'Портокалов кейк' },
    descriptions: { pl: 'Wilgotne ciasto pomarańczowe z ciasta filo.', nl: 'Vochtige sinaasappeltaart gemaakt van filo deeg.', el: 'Ζουμερή πορτοκαλόπιτα με φύλλο.', tr: 'Filo hamurundan nemli portakallı kek.', ar: 'كعكة برتقال رطبة مصنوعة من عجينة الفيلو.', bg: 'Портокалов кейк от фини кори.' }
  },
  {
    id: 'd3', category: 'desserts', price: 7.00,
    image: '/Griekse Baklava.png',
    names: { pl: 'Sernik', nl: 'Cheesecake', el: 'Τσιζκέικ', tr: 'Cheesecake', ar: 'تشيز كيك', bg: 'Чийзкейк' },
    descriptions: { pl: 'Kremowy sernik z owocową nutą.', nl: 'Romige cheesecake met een fruitige touch.', el: 'Κρεμώδες τσιζκέικ με φρουτώδη νότα.', tr: 'Meyve dokunuşlu kremsi cheesecake.', ar: 'تشيز كيك كريمي مع لمسة فاكهية.', bg: 'Кремообразен чийзкейк с плодов нюанс.' }
  },
  {
    id: 'd4', category: 'desserts', price: 7.00,
    image: '/Griekse Baklava.png',
    names: { pl: 'Grecka baklawa', nl: 'Griekse Baklava', el: 'Μπακλαβάς', tr: 'Baklava', ar: 'بقلاوة يونانية', bg: 'Гръцка баклава' },
    descriptions: { pl: 'Warstwy ciasta filo z miodem i orzechami.', nl: 'Lagen filo deeg met honing en noten.', el: 'Στρώσεις φύλλου με μέλι και καρύδια.', tr: 'Bal ve fındıklı filo hamuru katmanları.', ar: 'طبقات من عجينة الفيلو بالعسل والمكسرات.', bg: 'Гръцка баклава.' }
  },
];
